//! # Git Diff Algorithm Implementation Module
//!
//! This module implements the core diff functionality for comparing file contents and
//! repository states. It uses the Myers diff algorithm for efficient line-by-line
//! comparison of text files.
//!
//! ## Overview
//!
//! The diff system provides:
//! - Line-by-line comparison of file contents
//! - Detection of additions, deletions, and modifications
//! - Support for unified diff output format
//! - Comparison between commits, trees, or working directory
//!
//! ## Myers Algorithm
//!
//! The Myers diff algorithm is an O(ND) algorithm that finds the minimum number of
//! edits (insertions, deletions) to transform one sequence into another. It's
//! particularly efficient for finding differences in text files.
//!
//! ## Features
//!
//! - `diff_files()`: Compares two files and returns diff output
//! - `diff_commits()`: Compares two commits or trees
//! - Myers algorithm implementation for sequence comparison
//! - Unified diff formatting functions
//! - Support for binary file detection
//! - Performance optimizations for large files
//! - Integration with repository object database
//!
//! ## Usage
//!
//! Used by the `diff` porcelain command and internally for operations like
//! `status` and `commit` to show changes.

use hex;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

use crate::error::GritError;
use crate::plumbing::checkout::TreeEntry;
use crate::plumbing::objects;
use crate::repository::Repository;

#[derive(Debug, Clone, PartialEq)]
pub enum DiffStatus {
    /// File was added in the new tree compared to the old tree
    Added,
    /// File was removed in the new tree compared to the old tree
    Deleted,
    /// File exists in both trees but content has changed
    Modified,
    /// File exists in both trees but type changed (file ↔ directory)
    TypeChange,
}

/// Represents a single difference between two tree objects.
///
/// A diff entry captures the changes between two versions of a file or directory.
/// It contains the path, file modes, content hashes, and the type of change that occurred.
/// This structure is used by the diff algorithm to report what has changed between
/// two commits or trees.
///
/// # Fields
///
/// * `path` - The file or directory path where the change occurred
/// * `mode_a` / `mode_b` - File modes (permissions) in the two trees being compared
/// * `hash_a` / `hash_b` - Content hashes for the two versions
/// * `status` - The type of change (Added, Modified, Deleted, etc.)
///
/// # Usage
///
/// Diff entries are typically generated by comparing two tree objects and are used
/// to display changes between commits or show working directory status. The status
/// field indicates whether files were added, modified, deleted, or had type changes.
#[derive(Debug, Clone)]
pub struct DiffEntry {
    pub path: PathBuf,
    pub mode_a: u32,
    pub hash_a: String,
    pub mode_b: u32,
    pub hash_b: String,
    pub status: DiffStatus,
}

/// Compare two tree objects and return the differences between them
///
/// This function recursively compares two Git tree objects, identifying files that have been
/// added, modified, or deleted between the two trees. It handles nested directories by
/// recursively comparing subtrees when both trees contain a directory with the same name.
///
/// # Arguments
///
/// * `repo` - The repository containing the tree objects
/// * `tree_hash_a` - The SHA-1 hash of the first tree to compare
/// * `tree_hash_b` - The SHA-1 hash of the second tree to compare
/// * `prefix` - The path prefix for the current comparison level
///
/// # Returns
///
/// Returns a `Result` containing a vector of `DiffEntry` objects representing the differences,
/// or a `GritError` if reading trees fails.
///
/// # Examples
///
/// ```rust,no_run
/// use std::path::Path;
/// use grit::repository::Repository;
/// use grit::plumbing::diff::compare_trees;
///
/// let repo = Repository::new(Path::new("/repo"));
/// let diffs = compare_trees(&repo, "tree1_hash", "tree2_hash", Path::new("")).unwrap();
/// for diff in diffs {
///     println!("{}: {:?}", diff.path.display(), diff.status);
/// }
/// ```
pub fn compare_trees(
    repo: &Repository,
    tree_hash_a: &str,
    tree_hash_b: &str,
    prefix: &Path,
) -> Result<Vec<DiffEntry>, GritError> {
    let tree_a = objects::read_tree(repo, tree_hash_a)?;
    let tree_b = objects::read_tree(repo, tree_hash_b)?;

    let entries_a: HashMap<&str, &TreeEntry> = tree_a
        .entries
        .iter()
        .map(|e| (e.name.as_str(), e))
        .collect();
    let entries_b: HashMap<&str, &TreeEntry> = tree_b
        .entries
        .iter()
        .map(|e| (e.name.as_str(), e))
        .collect();

    let mut diffs = Vec::new();

    // Handle entries only in A (deletions)
    for (name, entry_a) in &entries_a {
        if !entries_b.contains_key(name) {
            let full_path = prefix.join(name);
            let mode_a = u32::from_str_radix(&entry_a.mode, 8).unwrap_or(0);
            diffs.push(DiffEntry {
                path: full_path,
                mode_a,
                hash_a: hex::encode(entry_a.hash),
                mode_b: 0,
                hash_b: String::new(),
                status: DiffStatus::Deleted,
            });
        }
    }

    // Handle entries only in B (additions) and in both
    for (name, entry_b) in &entries_b {
        let full_path = prefix.join(name);
        if let Some(entry_a) = entries_a.get(name) {
            // In both
            if entry_a.hash != entry_b.hash {
                let mode_a = u32::from_str_radix(&entry_a.mode, 8).unwrap_or(0);
                let mode_b = u32::from_str_radix(&entry_b.mode, 8).unwrap_or(0);
                diffs.push(DiffEntry {
                    path: full_path,
                    mode_a,
                    hash_a: hex::encode(entry_a.hash),
                    mode_b,
                    hash_b: hex::encode(entry_b.hash),
                    status: if mode_a != mode_b {
                        DiffStatus::TypeChange
                    } else {
                        DiffStatus::Modified
                    },
                });
            }
            // If same, do nothing
        } else {
            // Only in B
            let full_path = prefix.join(name);
            let mode_b = u32::from_str_radix(&entry_b.mode, 8).unwrap_or(0);
            diffs.push(DiffEntry {
                path: full_path,
                mode_a: 0,
                hash_a: String::new(),
                mode_b,
                hash_b: hex::encode(entry_b.hash),
                status: DiffStatus::Added,
            });
        }
    }

    // Recurse into subtrees
    for (name, entry_a) in &entries_a {
        if let Some(entry_b) = entries_b.get(name) {
            let mode_a = u32::from_str_radix(&entry_a.mode, 8).unwrap_or(0);
            let mode_b = u32::from_str_radix(&entry_b.mode, 8).unwrap_or(0);
            if mode_a == 0o040000 && mode_b == 0o040000 && entry_a.hash != entry_b.hash {
                let sub_diffs = compare_trees(
                    repo,
                    &hex::encode(entry_a.hash),
                    &hex::encode(entry_b.hash),
                    &prefix.join(name),
                )?;
                diffs.extend(sub_diffs);
            }
        }
    }

    Ok(diffs)
}

/// Generate unified diff output for two file contents
///
/// This function computes the differences between two text files using a line-by-line comparison.
/// It produces output in the standard unified diff format, similar to `diff -u`, and also returns
/// statistics about the number of insertions and deletions.
///
/// The algorithm processes the files line by line, identifying common lines and changes.
/// It handles additions, deletions, and modifications efficiently.
///
/// # Arguments
///
/// * `content_a` - The content of the first file as a string
/// * `content_b` - The content of the second file as a string
/// * `path` - The file path to include in the diff headers
///
/// # Returns
///
/// Returns a tuple containing:
/// - The unified diff output as a string
/// - The number of insertions (lines added)
/// - The number of deletions (lines removed)
///
/// # Examples
///
/// ```rust,no_run
/// use std::path::Path;
/// use grit::plumbing::diff::get_file_deltas;
///
/// let old_content = "line1\nline2\nline3\n";
/// let new_content = "line1\nline2_modified\nline3\nline4\n";
/// let path = Path::new("example.txt");
///
/// let (diff, insertions, deletions) = get_file_deltas(old_content, new_content, path);
/// println!("{}", diff);
/// println!("+{} -{}", insertions, deletions);
/// ```
pub fn get_file_deltas(content_a: &str, content_b: &str, path: &Path) -> (String, usize, usize) {
    let lines_a: Vec<&str> = content_a.lines().collect();
    let lines_b: Vec<&str> = content_b.lines().collect();

    let mut output = format!("--- a/{}\n+++ b/{}\n", path.display(), path.display());
    let mut insertions = 0;
    let mut deletions = 0;

    let mut i = 0;
    let mut j = 0;

    while i < lines_a.len() && j < lines_b.len() {
        if lines_a[i] == lines_b[j] {
            i += 1;
            j += 1;
        } else {
            // Find the end of the difference
            let start_i = i;
            let start_j = j;
            while i < lines_a.len() && j < lines_b.len() && lines_a[i] != lines_b[j] {
                i += 1;
                j += 1;
            }
            let del_count = i - start_i;
            let add_count = j - start_j;
            deletions += del_count;
            insertions += add_count;
            output.push_str(&format!(
                "@@ -{},{} +{},{} @@\n",
                start_i + 1,
                del_count,
                start_j + 1,
                add_count
            ));
            for line in lines_a.iter().take(i).skip(start_i) {
                output.push_str(&format!("-{}\n", line));
            }
            for line in lines_b.iter().take(j).skip(start_j) {
                output.push_str(&format!("+{}\n", line));
            }
        }
    }

    // Handle remaining lines
    if i < lines_a.len() {
        let del_count = lines_a.len() - i;
        deletions += del_count;
        output.push_str(&format!(
            "@@ -{},{} +{},{} @@\n",
            i + 1,
            del_count,
            j + 1,
            0
        ));
        for line in lines_a.iter().skip(i) {
            output.push_str(&format!("-{}\n", line));
        }
    }
    if j < lines_b.len() {
        let add_count = lines_b.len() - j;
        insertions += add_count;
        output.push_str(&format!(
            "@@ -{},{} +{},{} @@\n",
            i + 1,
            0,
            j + 1,
            add_count
        ));
        for line in lines_b.iter().skip(j) {
            output.push_str(&format!("+{}\n", line));
        }
    }

    (output, insertions, deletions)
}
